walkdir and read-only modifications
JuliaAPlavin/OpenScienceFramework.jl pull request #3
Opened 2024-09-05 16:06 UTC by behinger

2024-09-05 21:07 UTC, aplavin requested changes
Should be fine with some minor comments!

But please revert all the formatting (whitespace) changes – they are unrelated to this PR.

2024-09-05 21:07 UTC, aplavin commented on src/highlevel.jl
> +import Base.walkdir
that's not needed

2024-09-05 21:07 UTC, aplavin commented on src/highlevel.jl
> +Base.walkdir(proj::Project; kwargs...) = walkdir(directory(proj, ""); kwargs...)
more generic solution that is probably better:
- remove this method
- make `dir::Union{Directory,Project}` in the method below
- add `readdir(::Project)`
It'll work then I think, without a separate walkdir() method.

2024-09-09 08:42 UTC, behinger commented on src/highlevel.jl
> +Base.walkdir(proj::Project; kwargs...) = walkdir(directory(proj, ""); kwargs...)
I resolved this in the other PR. Note that the channel is now a `Channel::Union{Project,Directory})` due to your suggested change

2024-09-09 08:42 UTC, closed without merging

2024-09-09 08:42 UTC, behinger commented
I close this PR in favor of #4